version: '3'

run: when_changed

tasks:
  setup:
    status:
      - test -d .venv
      - test -d .vercel
    cmds:
      - uv venv
      - uv pip install mkdocs
      - |
        npx --yes \
          vercel --token "$VERCEL_TOKEN" \
            link --yes \
              --project esperoj

  build:
    deps:
      - task: setup
    desc: Build the site
    cmds:
      - uv run mkdocs build

  deploy:
    desc: Deploy
    deps: [build]
    cmds:
      - |
        npx --yes \
          vercel --token "$VERCEL_TOKEN" \
            deploy --yes --prod

  clean:
    desc: Clean up build artifacts
    cmds:
      - rm -rf site

  all:
    desc: Build, Deploy, and Clean
    cmds:
      - task: build
      - defer: { task: clean }
      - task: deploy
